name = "InverterProblem"
uuid = "9c1a4858-f2d2-429a-b643-6eda7b30b65b"
authors = ["Mark Hildebrand <mhildebrand@ucdavis.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
